apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.type }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.target_type }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ include "sample-app.fullname" . }}
          servicePort: {{ .Values.service.port }}
